### ISSUE TITLE
the '--diffcheck' manpage of iblinkinfo is misleading

### ISSUE THREAD

**Issue by ghost** [linux-rdma/infiniband-diags#14]
[snip]
       --diffcheck <key(s)> Specify what diff checks should be done in the --diff option above.  Comma separate multiple diff check key(s).  The available
       diff  checks  are: sw = switches, ca = channel adapters, router = routers, port = port connections, lid = lids, nodedesc = node descriptions.  Note
       that port, lid, and nodedesc are checked only for the node types that are specified (e.g. sw, ca, router).  If port is specified alongside  lid  or
       nodedesc, remote port lids and node descriptions will also be compared.
[end of snip]

The sentence "The available diff  checks  are: sw = switches, ca = channel adapters, router = routers, port = port connections, lid = lids, nodedesc = node descriptions." make users think there are six keys available for "--diffcheck".

1 sw
2 ca
3 router
4 port
5 lid
6 nodedesc

In fact, "sw", "ca", "router" are node types. "sw" and "ca" are specified by "--switches-only" and "--cas-only". Can't specify "route" as only type for iblinkinfo. 

[snip of infiniband-diags/src/iblinkinfo.c]
```c
static int process_opt(void *context, int ch, char *optarg)
{
.............
        case 4:
                diffcheck_flags = 0;
                p = strtok(optarg, ",");
                while (p) {
                        if (!strcasecmp(p, "port"))
                                diffcheck_flags |= DIFF_FLAG_PORT_CONNECTION;
                        else if (!strcasecmp(p, "state"))
                                diffcheck_flags |= DIFF_FLAG_PORT_STATE;
                        else if (!strcasecmp(p, "lid"))
                                diffcheck_flags |= DIFF_FLAG_LID;
                        else if (!strcasecmp(p, "nodedesc"))
                                diffcheck_flags |= DIFF_FLAG_NODE_DESCRIPTION;
                        else {
                                fprintf(stderr, "invalid diff check key: %s\n",
                                        p);
                                return -1;
                        }
                        p = strtok(NULL, ",");
                }
                break;
```c
[snip]

The section of "--diffcheck" documentation should be updated as:
======
      --diffcheck <key(s)> Specify what diff checks should be done in the --diff option above.  Comma separate multiple diff check key(s).  The available
       diff  checks  are: port = port connections, state = port state, lid = lids, nodedesc = node descriptions.  Note
       that port, state, lid, and nodedesc are checked only for the node types that are specified (e.g. switch, channel adapter, router).  If port is specified alongside  lid  or
       nodedesc, remote port lids and node descriptions will also be compared.
======

**Comment by weiny2** [comment]
Proposed fix in master-diffcheck branch.

**Comment by ghost** [comment]
The latest release was made one year ago. Can you please create a new release for infiniband-diags? thanks
