### ISSUE TITLE
Questions about the PortCountersExtended general services attribute

### ISSUE THREAD

**Issue by bsnapko** [linux-rdma/infiniband-diags#16]
Hello,

I have a couple questions about the PortCountersExtended general services attribute and how it is reported via the perfquery command.
The perfquery command with the "-x" option reports these counters

Example output from a RHEL75 perfquery -x command :
```
# perfquery -x 10 1
# Port extended counters: Lid 10 port 1 (CapMask: 0x5300 CapMask2: 0x0000002)
PortSelect:......................1
CounterSelect:...................0x0000
PortXmitData:....................0
PortRcvData:.....................0
PortXmitPkts:....................0
PortRcvPkts:.....................0
PortUnicastXmitPkts:.............0
PortUnicastRcvPkts:..............0
PortMulticastXmitPkts:...........0
PortMulticastRcvPkts:............0
CounterSelect2:..................0x00000000
SymbolErrorCounter:..............0
LinkErrorRecoveryCounter:........0
LinkDownedCounter:...............0
PortRcvErrors:...................0
PortRcvRemotePhysicalErrors:.....0
PortRcvSwitchRelayErrors:........0
PortXmitDiscards:................0
PortXmitConstraintErrors:........0
PortRcvConstraintErrors:.........0
LocalLinkIntegrityErrors:........0
ExcessiveBufferOverrunErrors:....0
VL15Dropped:.....................0
PortXmitWait:....................0
QP1Dropped:......................0

```
I used section 16.1.4.11 from the InfiniBand volume 1 for reference. 
The PortCountersExtended packet contains approximately 72 bytes of data.
It looks like the last data field would be PortMulticastRcvPkts.

What is going on after this field is printed? 
In the example output above a variable named CounterSelect2 is printed and then followed by what looks to me as the values from the PortCounters attribute. 
I am wondering if after the field PortMultiCastRcvPkts, is there valid data expected?

I did not find the fields printed after the CounterSelect2 listed in the PortCountersExtended section in the InfiniBand specification. 
Is there an annex to the specification for this attribute that indicates the fields following the PortMultiCastRcvPkts are valid? 

Attempting to follow to the perfquery code path, the libibmad function mad_dump_perfcounters_ext in the file libibmad/src/dump.c might be used to print the PortCountersExtended fields.

Is it the purpose of the second call to the _dump_fields function in the mad_dump_perfcounters_ext function to decode a set of fields in the MAD after the last PortCountersExtended field?

Thank you for your help.
Bill

**Comment by hnrose** [comment]
Beyond IBA 1.3, this attribute was extended, such extensions being optional. The additional counters in this attribute are indicated as to whether they're supported by PerfMgt ClassPortInfo CapabilityMask2 bit 1 (IsAdditionalPortCountersExtendedSupported). The additional counters are the 64 bit versions of the missing mandatory counters from PortCounters which might have been 4, 8, 16, or 32 bits there.

**Comment by bsnapko** [comment]
Thank you for the response. I have some follow up questions. 

> Beyond IBA 1.3, this attribute was extended, such extensions being optional.

What does beyond IBA 1.3 mean? I am asking how does one find more details about this extension. 
Is there a document describing how this attribute was extended? 
Could you please tell me when was this attribute extended? 
I did not find mention of this extension in the MgtWGErrata_120716 document. I could have missed it in the document. 

If the PerfMgt ClassPortInfo CapabilityMask2 bit 1 is zero, this means these optional extended counters are not supported. Is this correct? 
And the values should be reported as zero? 

Thank you for your help.

**Comment by hnrose** [comment]
> Thank you for the response. I have some follow up questions.
> 
> Beyond IBA 1.3, this attribute was extended, such extensions being optional.
> 
> What does beyond IBA 1.3 mean? 

IBA 1.3 is InfiniBand architecture release 1.3 (in this case volume 1). Beyond IBA 1.3 means that there are approved errata heading towards the next IBA release (probably 1.4).

> I am asking how does one find more details about this extension.
> Is there a document describing how this attribute was extended?

This is documented at the IBTA within the MgtWG (Management Working Group).
If your company is a member, you can get the updated documents. 

> Could you please tell me when was this attribute extended?

The errata for this enhancement was approved back in November 2016.

> I did not find mention of this extension in the MgtWGErrata_120716 document. I could have missed it in the document.

These are the errata against IBA 1.2.1 that went into making IBA 1.3.

> If the PerfMgt ClassPortInfo CapabilityMask2 bit 1 is zero, this means these optional extended counters are not supported. Is this correct?

Yes

> And the values should be reported as zero?

Unfortunately, the spec doesn't/couldn't mandate that as the remainder of the attribute (in terms of the 256 byte MAD) was not indicated as reserved. But IMO a better implementation is to clear out what was the remaining space in the MAD.

> Thank you for your help.

**Comment by weiny2** [comment]
Sounds like all your questions were answered.  Closing this comment.
