### ISSUE TITLE
Creating debian package for inifinband-diag tools

### ISSUE THREAD

**Issue by sbates130272** [linux-rdma/infiniband-diags#2]
Hi

I was informed this is the upstream version of inifiband-diags now [1]. Is it possible to get information on how to construct the debian package for this repo? Ideally it would be great if this could be added to the README.

Cheers

Stephen

[1] https://marc.info/?l=linux-rdma&m=150654763803090&w=2

**Comment by weiny2** [comment]
Unfortunately I have never made debian packages for this repo.  AsI don't know how.  I would be happy to add debian packaging (and/or instructions) to the repo if someone wants to submit it.

**Comment by weiny2** [comment]
Closing this issue.  As I said I would be happy to add debian packaging if someone who understands it better can provide it.
