### ISSUE TITLE
/usr/sbin/ibclearerrors and /usr/sbin/ibclearcounters should be in the compat package

### ISSUE THREAD

**Issue by ghost** [linux-rdma/infiniband-diags#3]
/usr/sbin/ibclearerrors
/usr/share/man/man8/ibclearerrors.8.gz
/usr/sbin/ibclearcounters
/usr/share/man/man8/ibclearcounters.8.gz

These two commands are deprecated, so they and corresponding manpages should be in the compat package. If you run 'configure' command  the package without the '--enable-compat-utils' flag. rpmbuild will failed as files are missing.

    File not found: /home/test/rpmbuild/BUILDROOT/infiniband-diags-2.0.0-1.el7.x86_64/usr/sbin/ibclearerrors
    File not found: /home/test/rpmbuild/BUILDROOT/infiniband-diags-2.0.0-1.el7.x86_64/usr/share/man/man8/ibclearerrors.8.gz
    File not found: /home/test/rpmbuild/BUILDROOT/infiniband-diags-2.0.0-1.el7.x86_64/usr/sbin/ibclearcounters
    File not found: /home/test/rpmbuild/BUILDROOT/infiniband-diags-2.0.0-1.el7.x86_64/usr/share/man/man8/ibclearcounters.8.gz

**Comment by weiny2** [comment]
proposed fix in https://github.com/linux-rdma/infiniband-diags/pull/13

**Comment by weiny2** [comment]
Fixed with #13
